{"msgs": [{"op": "AddElement", "path": [], "args": [{"rm": "rm-3", "type": "Prepared"}]}], "rmState": [{"op": "Update", "path": ["rm-3"], "args": ["prepared"]}]}
{"msgs": [{"op": "AddElement", "path": [], "args": [{"type": "Prepared", "rm": "rm-6"}]}], "rmState": [{"op": "Update", "path": ["rm-6"], "args": ["prepared"]}]}
{"msgs": [{"op": "AddElement", "path": [], "args": [{"rm": "rm-12", "type": "Prepared"}]}], "rmState": [{"op": "Update", "path": ["rm-12"], "args": ["prepared"]}]}
{"msgs": [{"op": "AddElement", "path": [], "args": [{"rm": "rm-2", "type": "Prepared"}]}], "rmState": [{"op": "Update", "path": ["rm-2"], "args": ["prepared"]}]}
{"msgs": [{"op": "AddElement", "path": [], "args": [{"type": "Prepared", "rm": "rm-10"}]}], "rmState": [{"op": "Update", "path": ["rm-10"], "args": ["prepared"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-3"]}]}
{"msgs": [{"op": "AddElement", "path": [], "args": [{"type": "Prepared", "rm": "rm-1"}]}], "rmState": [{"op": "Update", "path": ["rm-1"], "args": ["prepared"]}]}
{"msgs": [{"op": "AddElement", "path": [], "args": [{"rm": "rm-9", "type": "Prepared"}]}], "rmState": [{"op": "Update", "path": ["rm-9"], "args": ["prepared"]}]}
{"msgs": [{"op": "AddElement", "path": [], "args": [{"type": "Prepared", "rm": "rm-11"}]}], "rmState": [{"op": "Update", "path": ["rm-11"], "args": ["prepared"]}]}
{"msgs": [{"op": "AddElement", "path": [], "args": [{"type": "Prepared", "rm": "rm-0"}]}], "rmState": [{"op": "Update", "path": ["rm-0"], "args": ["prepared"]}]}
{"msgs": [{"op": "AddElement", "path": [], "args": [{"rm": "rm-4", "type": "Prepared"}]}], "rmState": [{"op": "Update", "path": ["rm-4"], "args": ["prepared"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-12"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-2"]}]}
{"msgs": [{"op": "AddElement", "path": [], "args": [{"type": "Prepared", "rm": "rm-8"}]}], "rmState": [{"op": "Update", "path": ["rm-8"], "args": ["prepared"]}]}
{"msgs": [{"op": "AddElement", "path": [], "args": [{"rm": "rm-7", "type": "Prepared"}]}], "rmState": [{"op": "Update", "path": ["rm-7"], "args": ["prepared"]}]}
{"msgs": [{"op": "AddElement", "path": [], "args": [{"rm": "rm-14", "type": "Prepared"}]}], "rmState": [{"op": "Update", "path": ["rm-14"], "args": ["prepared"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-1"]}]}
{"msgs": [{"op": "AddElement", "path": [], "args": [{"type": "Prepared", "rm": "rm-13"}]}], "rmState": [{"op": "Update", "path": ["rm-13"], "args": ["prepared"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-9"]}]}
{"msgs": [{"op": "AddElement", "path": [], "args": [{"rm": "rm-5", "type": "Prepared"}]}], "rmState": [{"op": "Update", "path": ["rm-5"], "args": ["prepared"]}]}
{"msgs": [{"op": "AddElement", "path": [], "args": [{"type": "Prepared", "rm": "rm-15"}]}], "rmState": [{"op": "Update", "path": ["rm-15"], "args": ["prepared"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-6"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-3"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-1"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-12"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-10"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-7"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-2"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-8"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-13"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-11"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-6"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-3"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-9"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-0"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-5"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-6"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-9"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-11"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-10"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-14"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-15"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-7"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-10"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-3"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-2"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-1"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-11"]}]}
{"tmState": [{"op": "Unchanged", "path": [], "args": []}], "tmPrepared": [{"op": "AddElement", "path": [], "args": ["rm-4"]}]}
{"msgs": [{"op": "AddElement", "path": [], "args": [{"type": "Commit"}]}], "tmState": [{"op": "Update", "path": [], "args": ["done"]}]}
{"rmState": [{"op": "Update", "path": ["rm-11"], "args": ["committed"]}]}
{"rmState": [{"op": "Update", "path": ["rm-1"], "args": ["committed"]}]}
{"rmState": [{"op": "Update", "path": ["rm-15"], "args": ["committed"]}]}
{"rmState": [{"op": "Update", "path": ["rm-14"], "args": ["committed"]}]}
{"rmState": [{"op": "Update", "path": ["rm-12"], "args": ["committed"]}]}
{"rmState": [{"op": "Update", "path": ["rm-0"], "args": ["committed"]}]}
{"rmState": [{"op": "Update", "path": ["rm-6"], "args": ["committed"]}]}
{"rmState": [{"op": "Update", "path": ["rm-10"], "args": ["committed"]}]}
{"rmState": [{"op": "Update", "path": ["rm-8"], "args": ["committed"]}]}
{"rmState": [{"op": "Update", "path": ["rm-2"], "args": ["committed"]}]}
{"rmState": [{"op": "Update", "path": ["rm-5"], "args": ["committed"]}]}
{"msgs": [{"op": "AddElement", "path": [], "args": [{"type": "Abort"}]}], "tmState": [{"op": "Update", "path": [], "args": ["done"]}]}
{"rmState": [{"op": "Update", "path": ["rm-9"], "args": ["committed"]}]}
{"rmState": [{"op": "Update", "path": ["rm-4"], "args": ["committed"]}]}
{"rmState": [{"op": "Update", "path": ["rm-7"], "args": ["aborted"]}]}
{"rmState": [{"op": "Update", "path": ["rm-13"], "args": ["aborted"]}]}
{"rmState": [{"op": "Update", "path": ["rm-3"], "args": ["committed"]}]}